### ISSUE TITLE
Situation Prévention

### ISSUE THREAD

**Issue by francois2metz** [betagouv/eva#669]
- [x] Créer le squelette de la situation
- [x] Entraînement
- [x] Afficher les dangers dans une bulle
- [x] Permet d'évaluer le danger
- [x] Permet de prévenir le danger
- [x] Avoir les bonnes images de prévention
- [x] intégrer les consignes écrites (voir #667)
- [x] intégrer les consigne audio (voir #667) #732 
- [x] Gérer la fin (voir #670)
- [ ] Avoir le bâtiment Prévention dans l'accueil (voir #671)
- [x] Empeche de revenir sur des qualifications/prévention déjà faites
- [x] Intégration des écrans 
  - [x] écran évaluation
  - [x] écran prévention
