### ISSUE TITLE
[Admin] Remonter les métriques sécurités dans les stats

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#682]
Soit ajouter une page de stat dédiée, soit ajouter des colonnes dans la page de stat actuelle (voir la discussion ci-dessous).

ajouter les métriques suivantes : 
- [x] Temps Passé Dans L'entrainement betagouv/eva-serveur#319
- [x] Dangers Identifiés
- [x] Dangers Identifiés Avant Activation De L'aide N°1
- [x] Dangers Bien Qualifiés
- [x] Retours Sur Les Situations Déjà Qualifiées
- [ ] ~~Temps D'ouvertures De Zones De Danger (delai avant ouverture zone)~~
- [x] Temps Moyen D'ouverture De Zone De Danger (delai moyen avant ouverture en fait)
- [x] Retours Sur Les Zones Sans Danger
- [x] TempsPremièreOuvertureZone (temps de recherche des zone de danger) (une colonne par zone) betagouv/eva-serveur#320
- [x] TempsDOuvertureZoneDangerSuccesX (une colonne par zone) betagouv/eva-serveur#320
- [x] TempsTotalDOuvertureZoneDangerX (une colonne par zone) betagouv/eva-serveur#320
- [x] NombreErreurs

**Comment by etienneCharignon** [comment]
@Alexis-Akinyemi Est-ce que ce serai OK qu'on fasse une page de stat par situation ? (je cherche juste à réduire un peu le nombre de colonnes).

**Comment by Alexis-Akinyemi** [comment]
Oui à condition d'avoir des colonnes campagne et id répondant dans chacune de ces pages
