### ISSUE TITLE
[Admin] refactorer les métriques sécurité en mettant une règle par classe

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#699]
- [ ] temps_total betagouv/eva-serveur#359
- [ ] temps_entrainement betagouv/eva-serveur#359
- [x] nombre_dangers_bien_identifies betagouv/eva-serveur#327
- [x] nombre_danger_mal_identifies betagouv/eva-serveur#333
- [x] nombre_dangers_bien_identifies_avant_aide_1 betagouv/eva-serveur#327
- [x] nombre_bien_qualifies betagouv/eva-serveur#335
- [x] nombre_retours_deja_qualifies betagouv/eva-serveur#335
- [x] delai_ouvertures_zones_dangers betagouv/eva-serveur#352
- [x] delai_moyen_ouvertures_zones_dangers betagouv/eva-serveur#352
- [x] attention_visuo_spatiale betagouv/eva-serveur#327
- [x] nombre_reouverture_zone_sans_danger  betagouv/eva-serveur#346
- [ ] nombre_rejoue_consigne betagouv/eva-serveur#359
- [x] temps_bonnes_qualifications_dangers
- [x] temps_recherche_zones_dangers
- [x] temps_total_ouverture_zones_dangers
