### ISSUE TITLE
Situation Maintenance

### ISSUE THREAD

**Issue by morissetcl** [betagouv/eva#704]
Cette MES est la première partie du module **Illettrisme**:

Cette issue fait référence à la #587 et à #703 (pour le design)

- [x]  Créer le squelette de la situation #705
- [x]  Entraînement #717
- [x]  Ajouter la consigne #733
- [x] Afficher les mots une fois la situation démarrée
- [x]  Gérer l'affichage des mots #711 
- [x] Avoir les boutons gauche / droite #726 
- [x]  Gérer la fin  #716
- [x] Enregistrer les événements
- [ ] Avoir le bâtiment Maintenance dans l'accueil [Dans une issue a part]
- [x]  Intégration de l'image de fond  #715
- [x] Met le focus sur la situation pour pouvoir utiliser les flèches #718
- [x] Afficher les mots de manières aléatoires #719
