### ISSUE TITLE
Situation Livraison (illettrisme niveau 2)

### ISSUE THREAD

**Issue by francois2metz** [betagouv/eva#748]
- [x] Créer le squelette de la situation #749
- [x] Afficher les questions #749
- [x] Entrainement
- [x] intégrer les consignes écrites #761 
- [x] intégrer les consignes audio #764 
- [x] Avoir le bâtiment dans l'accueil #760 
- [x] Gérer la fin

Design et Illustrations : #702

**Comment by GaelleOttan** [comment]
Consigne: 

Vous êtes chargé.e des livraisons dans le parc. Vous devez effectuer les livraisons, mais vous rencontrez certaines contraintes : des mots sont par exemple effacés sur les colis, sur les pancartes qui vous indiquent le chemin, ou vous entendez mal vos interlocuteurs. Vous devez donc retrouver les mots manquants. Avant de commencer l'exercice, débutons par un entrainement.

Consigne intermédiaire: 

Vous avez terminé l'entrainement, Bravo! Vous pouvez maintenant commencer l'exercice en retrouvant les mots manquants.

**Comment by francois2metz** [comment]
@GaelleOttan Je n'ai pas trouvé la consigne audio.
