### ISSUE TITLE
Situation Illettrisme niveau 3 : Objets Trouvés

### ISSUE THREAD

**Issue by francois2metz** [betagouv/eva#776]
- [x] Créer le squelette de la situation #778 
- [x] Menu du téléphone https://github.com/betagouv/eva/pull/803
- [x] Permet de changer d'appli #805 
- [x] Désactive les apps une fois faites #807 
- [x] Agenda de l'entrainement #829
- [x] Agenda #823
- [x] Intégrer les sons de réponses de l'agenda #857
- [x] Photos #822 
- [x] Messages vocaux comprend un horaire #883
- [x] Messages vocaux fait un calcul #889
- [x] Messages Texte #831
- [x] Rappels #824 
- [x] Déverouillage du téléphone #847
- [x] Intégrer les questions de fins #832 
- [x] ajouter une transition avant de passer aux questions de la fin (voir #768 tous en bas) #856 
- [x] Intégrer le vrai accueil avec les icones https://github.com/betagouv/eva/pull/837
- [x] Intégrer le fond de l'accueil https://github.com/betagouv/eva/pull/838
- [x] Question de fin https://github.com/betagouv/eva/pull/810
- [x] Entraînement #818 
- [x] Pendant l'entrainement, afficher un message à droite du téléphone demandant de cliquer sur l'application agenda (et non le message de la vrai situation) #851
- [x] intégrer les consignes écrites #825 
- [x] intégrer les consignes audio #852
- [x] Avoir le bâtiment dans l'accueil #858
- [x] Gérer la fin https://github.com/betagouv/eva/pull/810
- [x] Envoyer les événements #849 et #860  et #888 
- [x] Nom de l'app a coté de la question #853
- [x] Précharger toutes les ressources #891 

Voir #697
