### ISSUE TITLE
Backoffice

### ISSUE THREAD

**Issue by Laurenmichel21** [betagouv/eva#903]
Besoins identifiés : 
- [x] Pouvoir sélectionner par date toutes les campagnes réalisés en y ajoutant  une sélection "date" dans le pavé filtre sur la page Admin Campagnes (cf : photo 2)  le but  est de pouvoir piloter le volume en fonction des semaines / mois ( rapport DGEFP) (voir issue #941)
- [x] Intégrer la donnée du code postal au moment de la création d'un compte dans le but d'un pilotage géographique ( demande DGEFP) (voir issue #942)
- [x] Ajouter une colonne "nombre de passation"  dans la page admin COMPTE le but étant de savoir le nombre de passation rattaché au compte ( à la structure)  (voir issue betagouv/eva-serveur#423)

**Comment by Laurenmichel21** [comment]
<img width="1246" alt="Capture d’écran 2020-04-21 à 16 27 52" src="https://user-images.githubusercontent.com/57912856/79877932-1faada80-83ed-11ea-8127-f70aa906593a.png">

**Comment by Laurenmichel21** [comment]
<img width="1240" alt="Capture d’écran 2020-04-21 à 16 25 12" src="https://user-images.githubusercontent.com/57912856/79877957-276a7f00-83ed-11ea-9747-1ba4c0c28ae3.png">

**Comment by etienneCharignon** [comment]
Pour moi, tout est terminé, concernant ce ticket. je le ferme.
