### ISSUE TITLE
MES Bienvenue (Auto-positionnement)

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva#907]
Aujourd'hui, ce questionnaire qui est sous forme papier est très apprécié des accompagnants et ils demandent une version numérique, en particulier en cette période de travaille à distance.

Il faudrait donc intégrer le questionnaires suivant : https://docs.google.com/document/d/1ZaES4OZzABGpItHqPLzzNWFjnxuKS9wT5zuzBjF-d3s/edit

Solution proposé : réutiliser la MES Bureau

- le paragraphe d'introduction est a intégrer dans la consigne
- une question par fiche
- pour la dernière question, on la découpe en 7 questions une première sur les questions de vue, ou l’on choisi entre plusieurs options et ensuite 6 fiches a répondre par Oui ou Non.
-  ajouter une question “Vous avez un trouble dys (dyslexie, dysorthographie, dysphasie, dyspraxie, dyscalculie, troubles d’attention avec ou sans hyperactivité, Les troubles spécifiques du développement des processus mnésiques) 

⚠️ Pour améliorer l'ergonomie, nous allons proposer un composant de type jauge pour choisir le chiffre entre 1 et 7. Ce travail sera suivi dans une autre issue moins prioritaire. #908

A faire:

- [x] Afficher la situation Bienvenue (#916)
- [x] Mettre le bon bâtiment pour la situation (voir #930)
- [x] Intégrer les questions en prod
- [ ] Intégrer les consignes audios (voir issue #921)
- [x] Intégrer un entrainement ? Non, il n'y a pas d'entrainement pour cette situation
- [x] Intégrer des illustrations de fond pour les questions (voir #929)

**Comment by laurenehoutin** [comment]
Il faudrait y ajouter une question “Vous avez un trouble dys (dyslexie, dysorthographie, dysphasie, dyspraxie, dyscalculie, troubles d’attention avec ou sans hyperactivité, Les troubles spécifiques du développement des processus mnésiques) sauf que je ne trouve pas d’issue (à part une dans le backlog mais du coup je pense que ca n’est pas adapté de mettre ça là)"

**Comment by etienneCharignon** [comment]
Merci Laurène, j'ai ajouté ce point dans la fiche de description de l'issue.

**Comment by etienneCharignon** [comment]
@laurenehoutin J'ai créé la dernière question sur les troubles dys, sur la prod : https://api.app.eva.beta.gouv.fr/admin/question_qcms/69de04f8-cd66-4a31-a6c4-928e4d419984

J'ai fais une question à répondre par oui ou non, mais peut-être voulais-tu une question ou l'on choisi la réponse parmi la liste des troubles ?

N'hésite pas à mettre à jour la question directement sur la prod (pour l'instant ces questions ne sont pas encore utilisées).

**Comment by laurenehoutin** [comment]
> @laurenehoutin J'ai créé la dernière question sur les troubles dys, sur la prod : https://api.app.eva.beta.gouv.fr/admin/question_qcms/69de04f8-cd66-4a31-a6c4-928e4d419984
> 
> J'ai fais une question à répondre par oui ou non, mais peut-être voulais-tu une question ou l'on choisi la réponse parmi la liste des troubles ?
> 
> N'hésite pas à mettre à jour la question directement sur la prod (pour l'instant ces questions ne sont pas encore utilisées).

Cool ! C'est très bien comme cela, mais ce qui serait encore mieux, c'est que les personnes qui répondent "oui" aient une question suivante "Quel trouble dys avez-vous ?" avec la liste.

**Comment by etienneCharignon** [comment]
> mais ce qui serait encore mieux, c'est que les personnes qui répondent "oui" aient une question suivante "Quel trouble dys avez-vous ?" avec la liste.

Aujourd'hui, nous n'avons pas :
- de moyen de conditionner l'affichage d'une question sur la réponse de la question précédente
- de formulaire ou l'on peut cocher plusieurs case (pour les gens qui ont plusieurs dys)

Compte tenu du travaille que ça représente d'ajouter tout ça, je propose qu'on adresse cette amélioration dans une issue dédiée. Qu'en penses-tu ?

**Comment by laurenehoutin** [comment]
> @laurenehoutin J'ai créé la dernière question sur les troubles dys, sur la prod : https://api.app.eva.beta.gouv.fr/admin/question_qcms/69de04f8-cd66-4a31-a6c4-928e4d419984
> 
> J'ai fais une question à répondre par oui ou non, mais peut-être voulais-tu une question ou l'on choisi la réponse parmi la liste des troubles ?
> 
> N'hésite pas à mettre à jour la question directement sur la prod (pour l'instant ces questions ne sont pas encore utilisées).

D'accord. Oui oui oui, bien sûr !

**Comment by etienneCharignon** [comment]
En fait, je préfère même ajouter une ligne dans le backlog.

**Comment by etienneCharignon** [comment]
J'ai ouvert une nouvelle issue pour suivre le reste à faire sur la consigne audio #943 

Je clos cette issue
